!_TAG_FILE_FORMAT	2	/extended format; --format=1 will not append ;" to lines/
!_TAG_FILE_SORTED	1	/0=unsorted, 1=sorted, 2=foldcase/
!_TAG_PROGRAM_AUTHOR	Darren Hiebert	/dhiebert@users.sourceforge.net/
!_TAG_PROGRAM_NAME	Exuberant Ctags	//
!_TAG_PROGRAM_URL	http://ctags.sourceforge.net	/official site/
!_TAG_PROGRAM_VERSION	5.8	//
asteriskBrush	/home/onionhuang/OpenFrameworks/apps/myApps/practice/src/ofApp.cpp	/^void asteriskBrush() {$/;"	f	signature:()
circleBrush	/home/onionhuang/OpenFrameworks/apps/myApps/practice/src/ofApp.cpp	/^void circleBrush() {$/;"	f	signature:()
currentPolyline	/home/onionhuang/OpenFrameworks/apps/myApps/practice/src/ofApp.cpp	/^static ofPolyline currentPolyline;$/;"	v	file:
dragEvent	/home/onionhuang/OpenFrameworks/apps/myApps/practice/src/ofApp.cpp	/^void ofApp::dragEvent(ofDragInfo dragInfo) {}$/;"	f	class:ofApp	signature:(ofDragInfo dragInfo)
dragEvent	/home/onionhuang/OpenFrameworks/apps/myApps/practice/src/ofApp.h	/^  void dragEvent(ofDragInfo dragInfo);$/;"	p	class:ofApp	access:public	signature:(ofDragInfo dragInfo)
draw	/home/onionhuang/OpenFrameworks/apps/myApps/practice/src/ofApp.cpp	/^void ofApp::draw() {$/;"	f	class:ofApp	signature:()
draw	/home/onionhuang/OpenFrameworks/apps/myApps/practice/src/ofApp.h	/^  void draw();$/;"	p	class:ofApp	access:public	signature:()
gotMessage	/home/onionhuang/OpenFrameworks/apps/myApps/practice/src/ofApp.cpp	/^void ofApp::gotMessage(ofMessage msg) {}$/;"	f	class:ofApp	signature:(ofMessage msg)
gotMessage	/home/onionhuang/OpenFrameworks/apps/myApps/practice/src/ofApp.h	/^  void gotMessage(ofMessage msg);$/;"	p	class:ofApp	access:public	signature:(ofMessage msg)
isSavingPDF	/home/onionhuang/OpenFrameworks/apps/myApps/practice/src/ofApp.cpp	/^static bool isSavingPDF;$/;"	v	file:
keyPressed	/home/onionhuang/OpenFrameworks/apps/myApps/practice/src/ofApp.cpp	/^void ofApp::keyPressed(int key) {$/;"	f	class:ofApp	signature:(int key)
keyPressed	/home/onionhuang/OpenFrameworks/apps/myApps/practice/src/ofApp.h	/^  void keyPressed(int key);$/;"	p	class:ofApp	access:public	signature:(int key)
keyReleased	/home/onionhuang/OpenFrameworks/apps/myApps/practice/src/ofApp.cpp	/^void ofApp::keyReleased(int key) {}$/;"	f	class:ofApp	signature:(int key)
keyReleased	/home/onionhuang/OpenFrameworks/apps/myApps/practice/src/ofApp.h	/^  void keyReleased(int key);$/;"	p	class:ofApp	access:public	signature:(int key)
lastPoint	/home/onionhuang/OpenFrameworks/apps/myApps/practice/src/ofApp.cpp	/^static ofVec2f lastPoint;$/;"	v	file:
leftMouseButtonPressed	/home/onionhuang/OpenFrameworks/apps/myApps/practice/src/ofApp.cpp	/^static bool leftMouseButtonPressed = false;$/;"	v	file:
main	/home/onionhuang/OpenFrameworks/apps/myApps/practice/src/main.cpp	/^int main() {$/;"	f	signature:()
minDistance	/home/onionhuang/OpenFrameworks/apps/myApps/practice/src/ofApp.cpp	/^static float minDistance = 10;$/;"	v	file:
mouseDragged	/home/onionhuang/OpenFrameworks/apps/myApps/practice/src/ofApp.cpp	/^void ofApp::mouseDragged(int x, int y, int button) {}$/;"	f	class:ofApp	signature:(int x, int y, int button)
mouseDragged	/home/onionhuang/OpenFrameworks/apps/myApps/practice/src/ofApp.h	/^  void mouseDragged(int x, int y, int button);$/;"	p	class:ofApp	access:public	signature:(int x, int y, int button)
mouseEntered	/home/onionhuang/OpenFrameworks/apps/myApps/practice/src/ofApp.cpp	/^void ofApp::mouseEntered(int x, int y) {}$/;"	f	class:ofApp	signature:(int x, int y)
mouseEntered	/home/onionhuang/OpenFrameworks/apps/myApps/practice/src/ofApp.h	/^  void mouseEntered(int x, int y);$/;"	p	class:ofApp	access:public	signature:(int x, int y)
mouseExited	/home/onionhuang/OpenFrameworks/apps/myApps/practice/src/ofApp.cpp	/^void ofApp::mouseExited(int x, int y) {}$/;"	f	class:ofApp	signature:(int x, int y)
mouseExited	/home/onionhuang/OpenFrameworks/apps/myApps/practice/src/ofApp.h	/^  void mouseExited(int x, int y);$/;"	p	class:ofApp	access:public	signature:(int x, int y)
mouseMoved	/home/onionhuang/OpenFrameworks/apps/myApps/practice/src/ofApp.cpp	/^void ofApp::mouseMoved(int x, int y) {}$/;"	f	class:ofApp	signature:(int x, int y)
mouseMoved	/home/onionhuang/OpenFrameworks/apps/myApps/practice/src/ofApp.h	/^  void mouseMoved(int x, int y);$/;"	p	class:ofApp	access:public	signature:(int x, int y)
mousePressed	/home/onionhuang/OpenFrameworks/apps/myApps/practice/src/ofApp.cpp	/^void ofApp::mousePressed(int x, int y, int button) {$/;"	f	class:ofApp	signature:(int x, int y, int button)
mousePressed	/home/onionhuang/OpenFrameworks/apps/myApps/practice/src/ofApp.h	/^  void mousePressed(int x, int y, int button);$/;"	p	class:ofApp	access:public	signature:(int x, int y, int button)
mouseReleased	/home/onionhuang/OpenFrameworks/apps/myApps/practice/src/ofApp.cpp	/^void ofApp::mouseReleased(int x, int y, int button) {$/;"	f	class:ofApp	signature:(int x, int y, int button)
mouseReleased	/home/onionhuang/OpenFrameworks/apps/myApps/practice/src/ofApp.h	/^  void mouseReleased(int x, int y, int button);$/;"	p	class:ofApp	access:public	signature:(int x, int y, int button)
ofApp	/home/onionhuang/OpenFrameworks/apps/myApps/practice/src/ofApp.h	/^class ofApp : public ofBaseApp {$/;"	c	inherits:ofBaseApp
ofApp::dragEvent	/home/onionhuang/OpenFrameworks/apps/myApps/practice/src/ofApp.cpp	/^void ofApp::dragEvent(ofDragInfo dragInfo) {}$/;"	f	class:ofApp	signature:(ofDragInfo dragInfo)
ofApp::dragEvent	/home/onionhuang/OpenFrameworks/apps/myApps/practice/src/ofApp.h	/^  void dragEvent(ofDragInfo dragInfo);$/;"	p	class:ofApp	access:public	signature:(ofDragInfo dragInfo)
ofApp::draw	/home/onionhuang/OpenFrameworks/apps/myApps/practice/src/ofApp.cpp	/^void ofApp::draw() {$/;"	f	class:ofApp	signature:()
ofApp::draw	/home/onionhuang/OpenFrameworks/apps/myApps/practice/src/ofApp.h	/^  void draw();$/;"	p	class:ofApp	access:public	signature:()
ofApp::gotMessage	/home/onionhuang/OpenFrameworks/apps/myApps/practice/src/ofApp.cpp	/^void ofApp::gotMessage(ofMessage msg) {}$/;"	f	class:ofApp	signature:(ofMessage msg)
ofApp::gotMessage	/home/onionhuang/OpenFrameworks/apps/myApps/practice/src/ofApp.h	/^  void gotMessage(ofMessage msg);$/;"	p	class:ofApp	access:public	signature:(ofMessage msg)
ofApp::keyPressed	/home/onionhuang/OpenFrameworks/apps/myApps/practice/src/ofApp.cpp	/^void ofApp::keyPressed(int key) {$/;"	f	class:ofApp	signature:(int key)
ofApp::keyPressed	/home/onionhuang/OpenFrameworks/apps/myApps/practice/src/ofApp.h	/^  void keyPressed(int key);$/;"	p	class:ofApp	access:public	signature:(int key)
ofApp::keyReleased	/home/onionhuang/OpenFrameworks/apps/myApps/practice/src/ofApp.cpp	/^void ofApp::keyReleased(int key) {}$/;"	f	class:ofApp	signature:(int key)
ofApp::keyReleased	/home/onionhuang/OpenFrameworks/apps/myApps/practice/src/ofApp.h	/^  void keyReleased(int key);$/;"	p	class:ofApp	access:public	signature:(int key)
ofApp::mouseDragged	/home/onionhuang/OpenFrameworks/apps/myApps/practice/src/ofApp.cpp	/^void ofApp::mouseDragged(int x, int y, int button) {}$/;"	f	class:ofApp	signature:(int x, int y, int button)
ofApp::mouseDragged	/home/onionhuang/OpenFrameworks/apps/myApps/practice/src/ofApp.h	/^  void mouseDragged(int x, int y, int button);$/;"	p	class:ofApp	access:public	signature:(int x, int y, int button)
ofApp::mouseEntered	/home/onionhuang/OpenFrameworks/apps/myApps/practice/src/ofApp.cpp	/^void ofApp::mouseEntered(int x, int y) {}$/;"	f	class:ofApp	signature:(int x, int y)
ofApp::mouseEntered	/home/onionhuang/OpenFrameworks/apps/myApps/practice/src/ofApp.h	/^  void mouseEntered(int x, int y);$/;"	p	class:ofApp	access:public	signature:(int x, int y)
ofApp::mouseExited	/home/onionhuang/OpenFrameworks/apps/myApps/practice/src/ofApp.cpp	/^void ofApp::mouseExited(int x, int y) {}$/;"	f	class:ofApp	signature:(int x, int y)
ofApp::mouseExited	/home/onionhuang/OpenFrameworks/apps/myApps/practice/src/ofApp.h	/^  void mouseExited(int x, int y);$/;"	p	class:ofApp	access:public	signature:(int x, int y)
ofApp::mouseMoved	/home/onionhuang/OpenFrameworks/apps/myApps/practice/src/ofApp.cpp	/^void ofApp::mouseMoved(int x, int y) {}$/;"	f	class:ofApp	signature:(int x, int y)
ofApp::mouseMoved	/home/onionhuang/OpenFrameworks/apps/myApps/practice/src/ofApp.h	/^  void mouseMoved(int x, int y);$/;"	p	class:ofApp	access:public	signature:(int x, int y)
ofApp::mousePressed	/home/onionhuang/OpenFrameworks/apps/myApps/practice/src/ofApp.cpp	/^void ofApp::mousePressed(int x, int y, int button) {$/;"	f	class:ofApp	signature:(int x, int y, int button)
ofApp::mousePressed	/home/onionhuang/OpenFrameworks/apps/myApps/practice/src/ofApp.h	/^  void mousePressed(int x, int y, int button);$/;"	p	class:ofApp	access:public	signature:(int x, int y, int button)
ofApp::mouseReleased	/home/onionhuang/OpenFrameworks/apps/myApps/practice/src/ofApp.cpp	/^void ofApp::mouseReleased(int x, int y, int button) {$/;"	f	class:ofApp	signature:(int x, int y, int button)
ofApp::mouseReleased	/home/onionhuang/OpenFrameworks/apps/myApps/practice/src/ofApp.h	/^  void mouseReleased(int x, int y, int button);$/;"	p	class:ofApp	access:public	signature:(int x, int y, int button)
ofApp::setup	/home/onionhuang/OpenFrameworks/apps/myApps/practice/src/ofApp.cpp	/^void ofApp::setup() {$/;"	f	class:ofApp	signature:()
ofApp::setup	/home/onionhuang/OpenFrameworks/apps/myApps/practice/src/ofApp.h	/^  void setup();$/;"	p	class:ofApp	access:public	signature:()
ofApp::update	/home/onionhuang/OpenFrameworks/apps/myApps/practice/src/ofApp.cpp	/^void ofApp::update() {$/;"	f	class:ofApp	signature:()
ofApp::update	/home/onionhuang/OpenFrameworks/apps/myApps/practice/src/ofApp.h	/^  void update();$/;"	p	class:ofApp	access:public	signature:()
ofApp::windowResized	/home/onionhuang/OpenFrameworks/apps/myApps/practice/src/ofApp.cpp	/^void ofApp::windowResized(int w, int h) {}$/;"	f	class:ofApp	signature:(int w, int h)
ofApp::windowResized	/home/onionhuang/OpenFrameworks/apps/myApps/practice/src/ofApp.h	/^  void windowResized(int w, int h);$/;"	p	class:ofApp	access:public	signature:(int w, int h)
polylines	/home/onionhuang/OpenFrameworks/apps/myApps/practice/src/ofApp.cpp	/^static std::vector<ofPolyline> polylines;$/;"	v	file:
setup	/home/onionhuang/OpenFrameworks/apps/myApps/practice/src/ofApp.cpp	/^void ofApp::setup() {$/;"	f	class:ofApp	signature:()
setup	/home/onionhuang/OpenFrameworks/apps/myApps/practice/src/ofApp.h	/^  void setup();$/;"	p	class:ofApp	access:public	signature:()
tangentBrush	/home/onionhuang/OpenFrameworks/apps/myApps/practice/src/ofApp.cpp	/^void tangentBrush() {$/;"	f	signature:()
triangleBrush	/home/onionhuang/OpenFrameworks/apps/myApps/practice/src/ofApp.cpp	/^void triangleBrush() {$/;"	f	signature:()
update	/home/onionhuang/OpenFrameworks/apps/myApps/practice/src/ofApp.cpp	/^void ofApp::update() {$/;"	f	class:ofApp	signature:()
update	/home/onionhuang/OpenFrameworks/apps/myApps/practice/src/ofApp.h	/^  void update();$/;"	p	class:ofApp	access:public	signature:()
windowResized	/home/onionhuang/OpenFrameworks/apps/myApps/practice/src/ofApp.cpp	/^void ofApp::windowResized(int w, int h) {}$/;"	f	class:ofApp	signature:(int w, int h)
windowResized	/home/onionhuang/OpenFrameworks/apps/myApps/practice/src/ofApp.h	/^  void windowResized(int w, int h);$/;"	p	class:ofApp	access:public	signature:(int w, int h)
